
MasqueDB = {
["namespaces"] = {
},
["profileKeys"] = {
["Taurengoat - Quel'Thalas"] = "Default",
["Mechagoat - Ragnaros"] = "Default",
["Dracthyrgoat - Ragnaros"] = "Default",
["Cashmoneydan - Quel'Thalas"] = "Default",
["Gonkast - Ragnaros"] = "Default",
["Gonkgud - Ragnaros"] = "Default",
["Mechagoat - Drakkari"] = "Default",
["Goblingoat - Ragnaros"] = "Default",
["Cashmoneydan - Ragnaros"] = "Default",
["Undeadgoat - Quel'Thalas"] = "Default",
["Highgoat - Quel'Thalas"] = "Default",
["Maghargoat - Quel'Thalas"] = "Default",
["Darkwoat - Ragnaros"] = "Default",
["Voidelfgoat - Ragnaros"] = "Default",
["Cashmoneyg - Ragnaros"] = "Default",
["Kultirangoat - Ragnaros"] = "Default",
["Draeneigoat - Ragnaros"] = "Default",
["Liktok - Quel'Thalas"] = "Default",
["Dwarfgoat - Ragnaros"] = "Default",
["Orcgoat - Quel'Thalas"] = "Default",
["Humangoat - Ragnaros"] = "Default",
["Nightgoat - Quel'Thalas"] = "Default",
["Mechagoatfr - Ragnaros"] = "Default",
["Darkgoat - Ragnaros"] = "Default",
["Gonkragger - Ragnaros"] = "Default",
["Gnomegoat - Ragnaros"] = "Default",
["Goblingoat - Quel'Thalas"] = "Default",
["Pandagoat - Ragnaros"] = "Default",
["Earthengoat - Ragnaros"] = "Default",
["Zandalargoat - Quel'Thalas"] = "Default",
["Vulperagoat - Quel'Thalas"] = "Default",
["Trollgoat - Ragnaros"] = "Default",
["Brusa - Ragnaros"] = "Default",
["Bloodelfgoat - Quel'Thalas"] = "Default",
["Highgoat - Ragnaros"] = "Default",
["Arianagrande - Thunderlord"] = "Default",
},
["profiles"] = {
["Default"] = {
["Groups"] = {
["WeakAuras_O30mQYI3YFn"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_OCmsJ8inVPG"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_fIcmiSg(0fY"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["Blizzard Action Bars_StanceBar"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["M33kAuras_L4nAZAp9LuI"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["M33kAuras_vlaDX6He4BE"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_apt8(xO(Eqy"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_1(DcrPr2Lbb"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_Td0UDtWfGOU"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_mlqWWGQrm(q"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_jiIp1QSNp12"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_Po17qo9tXy9"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["M33kAuras_4Bh8ZW(8C1O"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_t64(EvDmsEm"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_IlfDIVsoqL)"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["Bartender4_PetBar"] = {
["Backdrop"] = true,
["Upgraded"] = true,
["Colors"] = {
["Backdrop"] = {
0.5882353186607361,
0.415686309337616,
0.3294117748737335,
1,
},
},
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_zy(R50KjHm6"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_Uagy7x6s18N"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["M33kAuras_qSl8OF3GQx7"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["Bartender4_6"] = {
["Backdrop"] = true,
["Upgraded"] = true,
["Colors"] = {
["Backdrop"] = {
0.5882353186607361,
0.415686309337616,
0.3294117748737335,
1,
},
},
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_LMXmeKIdfAL"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_4Bh8ZW(8C1O"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_)(X2MUNAhlJ"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_QNKHN1ZY8tx"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["OPie"] = {
["Backdrop"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_IW(CBzWo(tT"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["Blizzard Action Bars_ActionBar"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["Blizzard Action Bars_PetBattleFrame"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_535jMZ0Ahvg"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_1Db4QYYrq0t"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_t9eCF5((cXD"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["Simple Assisted Combat Icon"] = {
["Backdrop"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_i)mxzOccN2N"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_znvEvvvfdLi"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_jFbwJbtnIIt"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_FwyHNz6hf0L"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["M33kAuras_NwCtZqW8kxF"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_h91Ju23gTxT"] = {
["Gloss"] = true,
["Upgraded"] = true,
["SkinID"] = "Blizzard Classic",
["Inherit"] = false,
},
["WeakAuras_LKbrzTqOlPL"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_AvxE3wBGFC)"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["Bagnon_guildbank - bags"] = {
["Gloss"] = true,
["Backdrop"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_dF9uhGJOBAu"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_cIV3o(tYix4"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_6N4Et2KjBIz"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_vGcZKsVrtSw"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_0JWLXHRlOPm"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["Blizzard Action Bars_ExtraAbilityContainer"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_3nFOVOJThnD"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras"] = {
["Gloss"] = true,
["Backdrop"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_IEJaBtUN6Zq"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_mC6O5KQ8Qdw"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_cdhVSmoRneR"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_If2MI1tewIc"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_H78gHVB3u(j"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["Blizzard Action Bars_MultiBarLeft"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_IzhktinAOGZ"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_s9Rpi3s5YDT"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_awONhgYk6jd"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_gOfOBBLql8Y"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_qlqq51zvyvI"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_SbPjswy36VV"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_dtSJdSFKLaV"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_SoPuuppXOsx"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_MjX6yTdZhHA"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_w6uljgv9D)H"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_jla(3(AkNDD"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["Blizzard Action Bars_MultiBar6"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_39n6D2zryli"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_Z7QkAcBqv8H"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["ConsolePort_|cffffff00Page|r: VehicleL"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_qSl8OF3GQx7"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_gpF8B5A5gyL"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_8LvzBFp2Fhm"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_2dKL3(QyR08"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_JFJza349IZW"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_(DCDbIBNf(b"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_SsuvcIYWfZ9"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_GwGEpomOsZo"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["UseScale"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
["Scale"] = 1.1,
},
["WeakAuras_APGnTYuRv2W"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_4EI6Tm4VRSr"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_XVLny6f2SLS"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["M33kAuras_AtO62xzLTHA"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_V6PluhmIl93"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_5rzH37yYwmq"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_kErbiCd889e"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_WKcdSrGvWYb"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_dKArlU3A7ZZ"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_OrJhkhruWvQ"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_jAUnsNOGY2P"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_sSY40jwyrlU"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_u4h4l7upSTm"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_URmiIcdA(GH"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_rle)ZEYDd23"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_o(tQ(39fg0c"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_67d1JnkXNER"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Trinity: Round",
["Inherit"] = false,
},
["WeakAuras_T((hASWVyx("] = {
["Scale"] = 0.8200000000000001,
["Backdrop"] = true,
["Upgraded"] = true,
["UseScale"] = true,
["SkinID"] = "Azerite",
["Inherit"] = false,
["Gloss"] = true,
},
["WeakAuras_XKDJMXajxKI"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_gSciPtL16Zj"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_THcXhD36aFn"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["GladiusEx_Debuffs"] = {
["Gloss"] = true,
["Backdrop"] = true,
["SkinID"] = "Blizzard Classic",
["Inherit"] = false,
},
["WeakAuras_UxaKBZ0eK7V"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["Bartender4_Flyout"] = {
["Backdrop"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_OWc5eYa6qQf"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["M33kAuras_CcvtlbTy7Cf"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["M33kAuras_lT7)fK956rg"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["Bagnon_inventory - items"] = {
["Gloss"] = true,
["Backdrop"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_2hDBnrsa9qz"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_L9pt2HDgNYj"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_g)m0pTLOdiK"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["M33kAuras_1p7G20kDNJI"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_g3P(z6Wxkhx"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_yTTVZSXYpcr"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_vlaDX6He4BE"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["Blizzard Buffs"] = {
["Backdrop"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_OdAb4p(r(AF"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_z1SToo8zAQI"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["M33kAuras_GwGEpomOsZo"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_DUTTI)MTOye"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_DmwaRpPoEwm"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_iC1q2uGiVIM"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_uzYVqIan5Ai"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["M33kAuras_JAgjbcNXZrR"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_5PbCELo78wD"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_O4t4BPlLhbx"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_2KAaWgWtwPT"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_cPmmjipqbtj"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_EJV1moVm6ZM"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_w2PcqGj(u7O"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_NGEVirzhxuf"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_UIevXomNyFl"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_MFWyRsIj1(9"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_Xr3wDysb5eT"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_kI9xB)i7oCA"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_VFqS(wY0w(f"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_rjkrACjkSAG"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_dpnSDVTh7G("] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["Bartender4_StanceBar"] = {
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_hFWX9VplCyr"] = {
["Gloss"] = true,
["Upgraded"] = true,
["SkinID"] = "Blizzard Classic",
["Inherit"] = false,
},
["WeakAuras_a08(3CP2mj("] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_sk4FfVTaqV5"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_fu50JIuSHFC"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_rAJnZ7QqADs"] = {
["Gloss"] = true,
["Upgraded"] = true,
["SkinID"] = "Blizzard Classic",
["Inherit"] = false,
},
["M33kAuras_juwoHv5XYm7"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_ZMgqG7TfxSE"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["Bagnon_inventory - bags"] = {
["Gloss"] = true,
["Backdrop"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_lpcgQTbfay3"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_q9n)kAkT2E("] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["Blizzard Action Bars_SpellFlyout"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_)Z0uBTYY(DL"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_XJWrSYLU2mY"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_un7Ozf(99Hr"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["M33kAuras_kErbiCd889e"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_2ROlG)2iSMA"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_xkXAF4imzv5"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_FPp8ARN5Ck1"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_T5APMmmIpC7"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_wKhgMRxdiG0"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["Blizzard Action Bars_BuffBarCooldownViewer"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_6P9UmGf7DRR"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["Blizzard Action Bars"] = {
["Gloss"] = true,
["Backdrop"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_cToinHiKXMi"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_8XsU(1UMY83"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_sjJfxves0ke"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_AgUsLMDfdfI"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["Bartender4_5"] = {
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["MA Blizzard Bags"] = {
["Gloss"] = true,
["Backdrop"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["ConsolePort"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_tzIx6xAfStS"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_r6VbVOpPQbu"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_Om3FI5yeHbs"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_1Sgb8k6EB4U"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_8nLpVmtrnpF"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_)4KXnO1jK0Y"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_I751ALkkwUA"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_mgbAGJ1dKEx"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_mS9G9vvVbv)"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_AxMyX6Rl2Ia"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_YXWVxt07dKj"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_(mcvr1)jvhm"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_k0mDQXP6LXZ"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_aEZJQF0cE7g"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_p2oo4qAqskB"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_MQydnLf8oHS"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["Bartender4_BagBar"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_t1XF54OZRj6"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_5j1svzgotM8"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_a8Q064(TZNQ"] = {
["Gloss"] = true,
["Upgraded"] = true,
["SkinID"] = "Blizzard Classic",
["Inherit"] = false,
},
["WeakAuras_EpwGC4GIMR)"] = {
["Gloss"] = true,
["Upgraded"] = true,
["SkinID"] = "Blizzard Classic",
["Inherit"] = false,
},
["Blizzard Action Bars_PetBar"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["M33kAuras_SdtR5vnFisi"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["OmniBar_Spear Hand Strike"] = {
["Gloss"] = true,
["Backdrop"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_y4WQrquT5GB"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_V9cQZTMSVtN"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["ConsolePort_|cffffff00Page|r: VehicleR"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_0oqxZezaZ0x"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_ZUfRLwRE1AQ"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_OBAESJpWXU0"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_LgV)l0Tz35E"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["Blizzard Action Bars_MultiBarBottomLeft"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["M33kAuras_2dKL3(QyR08"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_44hgFPXfAcD"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_8mJvBt4(DGg"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_sIFUu5WTo4W"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["M33kAuras_67d1JnkXNER"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["Bartender4"] = {
["Backdrop"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_54tt8zf0kn2"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_6UJrQMH5yhe"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_bSRSXZl9QKf"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_NX(q6ZkTJVy"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_MZtNL)lp32V"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_Puf6kTQ1SJt"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_iHThbUee0QC"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["Hekili"] = {
["Gloss"] = true,
["Backdrop"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_PD1uppYXGO5"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["HidingBar_DataBroker"] = {
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_OiziaB1ySBJ"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_K2aC22Al4HO"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_1gdhcBddIsO"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["Blizzard Action Bars_EssentialCooldownViewer"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_MWmNHIV1fvL"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_lIlDPZpjktr"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["HidingBar_MinimapButtons"] = {
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_NGm7YJh9uDd"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_phycsYcuPhq"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_Yn2MCwWl0(7"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_trp3ES7X)dw"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_GmHy9FKgTy1"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_YLVedDEeMI2"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_v1OxRDgpLqP"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_2IzLQWpmfgd"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["Baganator_Bag"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_SJ9UXXqyQ94"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_CXE87lQPBsl"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_Q0J4wKv2GIs"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_laOBUStkG)4"] = {
["Gloss"] = true,
["Upgraded"] = true,
["SkinID"] = "Blizzard Classic",
["Inherit"] = false,
},
["WeakAuras_SdtR5vnFisi"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["Bagnon_voidstorage - bags"] = {
["Gloss"] = true,
["Backdrop"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_glrE0glmtwK"] = {
["Scale"] = 0.75,
["Backdrop"] = true,
["Upgraded"] = true,
["UseScale"] = true,
["SkinID"] = "Azerite",
["Inherit"] = false,
["Gloss"] = true,
},
["WeakAuras_mqOxyXSWB2H"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_wIQFE5rNYzb"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_i1ouCV6k(rj"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_4dN7cTUgwqw"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_9vziNTZ0VVk"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_PoH8rurPbT5"] = {
["Gloss"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Blizzard Classic",
},
["WeakAuras_SwD9HEF2oQZ"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_9cl(5lu0mV7"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["M33kAuras_nMuZOccudDQ"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["Bagnon_bank - items"] = {
["Gloss"] = true,
["Backdrop"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_Bzpo7FpV0K("] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_O9QW6sPfHAA"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_cKI)L6cmhCi"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["Blizzard Action Bars_BuffIconCooldownViewer"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["Bartender4_3"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["Bagnon_bank - bags"] = {
["Gloss"] = true,
["Backdrop"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_sd5iEAgtqde"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["OmniBar_Avenger's Shield"] = {
["Gloss"] = true,
["Backdrop"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_)wi1oQoIWVg"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_yY4gJtdBpV3"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_UsfZmhogy4g"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_KwCTImakgot"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_QD2VpIoEGfs"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_pPxAkBKIF4e"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_yeMmZT3wEbM"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_gw7VCEkZKTB"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_5pmWXZTYwaT"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_dHvB9X543Vs"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["M33kAuras_4dN7cTUgwqw"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_Yx)B603jMut"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_(xz6XLQnM3u"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_kUIrsu(1TeR"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_SHsiBwViLeK"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_a9k7XQezEJs"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_KclkN3s70or"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["Bagnon"] = {
["Gloss"] = true,
["Backdrop"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["Blizzard Buffs_Debuffs"] = {
["Backdrop"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_7b6GsxChq66"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["Blizzard Action Bars_PossessBar"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_VtHRmfnrCFg"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_fRDUBZvLJrV"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_Ld1xtr4whYD"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_YVFhw5cmnjV"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_GJp9ebivU9z"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["RPGLootFeed"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["GladiusEx_Buffs"] = {
["Gloss"] = true,
["Backdrop"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["M33kAuras_MQydnLf8oHS"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_8paAB(DjNZ("] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["UseScale"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
["Scale"] = 1.1,
},
["WeakAuras_LEBhZBGkPLw"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_m7Zer2pTPGL"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_E8H(w0xIrYJ"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_ls6FpGh1ZC)"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_juwoHv5XYm7"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_4Sr6X6RcgZr"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_2YwUQBUElmT"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_54YexsuWBzM"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_u)fqTJ6n)I("] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_nXO1eQD(OVl"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_vDN9h43VC8M"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["NameplateSCT"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["HidingBar"] = {
["Backdrop"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_LIsH)vUGF15"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["M33kAuras_8paAB(DjNZ("] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_KwoVTTRUigI"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["Blizzard Action Bars_MultiBar5"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_yzS11ChaRYL"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_ALAv6grXtMT"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_1rXN5471NMB"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_tfVe5T3vuQF"] = {
["Gloss"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Blizzard Classic",
},
["WeakAuras_JX30VRYi0Nd"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_rd2AIjs2iRI"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_jlYlsuZsKP8"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_EPKKhWT(ZZz"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_Mh6D66K83U7"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["M33kAuras_rd2AIjs2iRI"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_uRLfuyb)qcw"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_j6EDPunZQc1"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["Bartender4_2"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_WA7bdG5a(Sm"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["Blizzard Action Bars_MultiBarRight"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_QMONTeqoCpd"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_TPPBLAkH14d"] = {
["Gloss"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Blizzard Classic",
},
["WeakAuras_4cUR3C5jtD7"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_oxKhaLLT9A9"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_qN3r5L7XLO9"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["M33kAuras"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_jWs82u1R99u"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_WRMz5j4WodE"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["M33kAuras_4cUR3C5jtD7"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_67ZkE1ZD3fD"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_kI6CAd0vvjq"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["M33kAuras_PoH8rurPbT5"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_bvkOY949)c7"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["M33kAuras_ZSLj97jV8A("] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_e9v2edm9PZv"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_jP8SEm43VrI"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_GfQ9yBRnzoo"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["Bartender4_7"] = {
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_6X4INToZHjw"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["Blizzard Buffs_Target Buffs"] = {
["Backdrop"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_AHCfjd5FPYd"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_MOt3vhQpQ(x"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_6VXMAPILBEm"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_5K4ADo5kl3G"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_JQ1vWc4uNqF"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_1CuHc1jKifq"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_sfESGbMFCU8"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_RmAJkz10fnp"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_u91VaQZqZBZ"] = {
["Gloss"] = true,
["Upgraded"] = true,
["SkinID"] = "Blizzard Classic",
["Inherit"] = false,
},
["WeakAuras_ePZUt9ezRTY"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_ImbUzKfPSCd"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_qPEGOyB(Eyb"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_y9eGAfLZ0w4"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_QYsTj0u(nKH"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_F(N4aZmIJbI"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_7JznjVo2Kio"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_VoWqCiM2adO"] = {
["Gloss"] = true,
["Upgraded"] = true,
["SkinID"] = "Blizzard Classic",
["Inherit"] = false,
},
["WeakAuras_aK8MXODz1pT"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_x)aAhkYQhVe"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["BigDebuffs_UnitFrame"] = {
["Gloss"] = true,
["Backdrop"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_3aP)UbiMSTF"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_eyVETjg7lg6"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["Blizzard Action Bars_UtilityCooldownViewer"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_LttdPMtbr1U"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_h4xjbf1YCzl"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_5xqgvGCZhuZ"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_ZSLj97jV8A("] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["GladiusEx"] = {
["Gloss"] = true,
["Backdrop"] = true,
["SkinID"] = "Blizzard Classic",
["Inherit"] = false,
},
["Blizzard Action Bars_MultiBar7"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_EDkSPA0dH0Q"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["M33kAuras_laOBUStkG)4"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_ScfbYj9CvIz"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_4oIOMlf)DmR"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_zpFrSmWsNA("] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_CcvtlbTy7Cf"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["OmniBar"] = {
["Gloss"] = true,
["Backdrop"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_EioawwL(Bso"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["OmniBar_Rebuke"] = {
["Gloss"] = true,
["Backdrop"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_yn9e0Jlh658"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_TemEMUqTzsH"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_gfc9eEjEEIn"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_tZko95nxIRq"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_5IVFwuN3Dae"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["M33kAuras_tfVe5T3vuQF"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_3W1)FWODyby"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_lP)wk(p(4yn"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_4hsJHyu)ch7"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_oNwea40KxC0"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_nMuZOccudDQ"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["HidingBar_CGButtons"] = {
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_EQxZbX3iuKH"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_vjnzNHjAPsC"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_Wm9sM5ISDeJ"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["Masque"] = {
["Backdrop"] = true,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_WkfIAs0TSzz"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_Wxi11TvOA2o"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_3QiydR8UQ2("] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_lHh8LFcPAUx"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_MU)f8)bl(n7"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_9(COOmb3ccY"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_yWinNnA9XQR"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["Bartender4_1"] = {
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_4PqNvQKRUF3"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_GtsfcH6S1Bl"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_sbUq(gpTAII"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_dQ5haiCHEtP"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["Baganator"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["Bagnon_guildbank - items"] = {
["Gloss"] = true,
["Backdrop"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["BigDebuffs_NamePlate"] = {
["Gloss"] = true,
["Backdrop"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_HBekyOv24ct"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["Bartender4_4"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_F)ba(LRykbS"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_ujj95ixiChQ"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_JAgjbcNXZrR"] = {
["Gloss"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Blizzard Classic",
},
["WeakAuras_tuOOnb9XScr"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_HN4KO5y5ciP"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_wcM3eQLgjdq"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_rNtj1BHdEq8"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_ASB1PmYQPPh"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_amUL7T1N0md"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_yDC(dvraKch"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_(vhpRogK5QU"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_)uIECQVbhA8"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_lrNHenDKRrD"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_kkNahL4S4xg"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_p9neDz0cex5"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_bWVc1591e)P"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_Mk18xgnyGzN"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_G4mLt4)1diS"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_HMTL2dqbdgB"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_F9fc366(ezn"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["BigDebuffs"] = {
["Gloss"] = true,
["Backdrop"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_ozqUM7SCfME"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["Blizzard Buffs_Buffs"] = {
["Backdrop"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["WeakAuras_hhiydCxG4zD"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["Blizzard Buffs_Target Debuffs"] = {
["Backdrop"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["M33kAuras_wcM3eQLgjdq"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_Qo0(Zea5gJw"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_Wj5cqqoV47o"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_KF33oGCRASk"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_OG3mUT(uHhb"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["M33kAuras_TPPBLAkH14d"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["M33kAuras_P)5g5Qhz)Gu"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_04dlgFqhUx6"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["Blizzard Action Bars_OverrideActionBar"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["Bagnon_voidstorage - items"] = {
["Gloss"] = true,
["Backdrop"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_9nWBm85v9BP"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["M33kAuras_Wm9sM5ISDeJ"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["M33kAuras_h91Ju23gTxT"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["Blizzard Action Bars_MultiBarBottomRight"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_cE)VTEcQLRr"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["Inherit"] = false,
["SkinID"] = "Azerite HEX",
},
["Blizzard Action Bars_CooldownViewer"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_LllAF5hn1aP"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_GQehUhW6uBP"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_R0B5ZgSm6c4"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_cAEqD8b1M3G"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_NwCtZqW8kxF"] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
["WeakAuras_DdDNHgNEMY("] = {
["Gloss"] = true,
["Backdrop"] = true,
["Upgraded"] = true,
["SkinID"] = "Azerite HEX",
["Inherit"] = false,
},
},
["LDB"] = {
["minimapPos"] = 171.3332803811111,
},
["API_VERSION"] = 110210,
},
},
}
